### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by TheoBIET** [yayouu/scroll_effect_css#1]
Un petit fork ou tag de la source d'où provient cette idée aurait été sympa :)
https://github.com/TheoBIET/O-Japon

**Comment by yayouu** [comment]
Yep sorry : )  de base c’était juste pour le montrer et j’aller supp   ducoup complétement oublier xd ( ps :j’ai fork c’est bon ; ))


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : ***@***.***>
Envoyé le :jeudi 22 avril 2021 12:53
À : ***@***.***>
Cc : ***@***.***>
Objet :[yayouu/scroll_effect_css] :) (#1)


Un petit fork ou tag de la source d'où provient cette idée aurait été sympa :)
https://github.com/TheoBIET/O-Japon

**Comment by TheoBIET** [comment]
aha thx ♥♥
